name: Cluster Flow
description: A pipelining tool to automate and standardise bioinformatics analyses on cluster environments
author: Phil Ewels
permalink: pretty
baseurl: /clusterflow
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, node_modules]


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"